# -*- coding: utf-8 -*-
"""Excercise3_64120015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNVOowcT9Nx8MP39RiX5fqSBsHtQgkrf

# 8 Build Circle area and Circle circumference by input r from input 
formular<br>
circle area = Pi\*r\*\*2<br>  
circle circumference = 2\*Pi\*r<br>
"""

import math

r = int(input("r = "))
print("circle area = " , (math.pi)*(r**2) )
print("circle circumference = ", 2 * (math.pi) * r)

"""# 9 Print odd number from 1 to 100"""

for i in range(0,101):
  if (i%2) != 0:
    print(i)

"""# 10 Print even numbers from 1 to 100 in list format"""

a=[]
for i in range(0,101):
  if (i%2) == 0:
    a.append(i)
print(a)

"""# 11 Please calculate sse from formula From listY = [1.9,4.2,6.5,7.4,11]
![r_squared_6.png](attachment:r_squared_6.png)
"""

y = [1.9,4.2,6.5,7.4,11]
mean = sum(y) / len(y)
for i in y:
  x = i - mean
  x = x**2
  a = a + x
print("SSE : ", a )

"""# 12 list1 = [1,1,2,2,3,3,4,4,5,5,6,6] ให้สร้าง list ใหม่ให้ค่าสมาชิกต้องไม่ซ้ำกัน"""

list1 = [1,1,2,2,3,3,4,4,5,5,6,6]
res = []
for i in list1:
    if i not in res:
        res.append(i)
print(res)

"""# 13 Build Dictionary with key is charactor and value is number and print some value in key """

dic = {
    "a":1,
    "b":2,
    "c":3
}
for i in dic:
  print(i," : ",dic[i])

"""# 14 Build Dictionary with key is english word and value is thai word and print out"""

dic = {
    "cat":"นก",
    "dog":"หมา",
    "bird":"นก"
}
for i in dic:
  print(i," : ",dic[i])

"""# 15 Build Contract Name and Number to Dictionary and have add delete lookup quit """

dic = {
    "name":"tanupat satitvattana",
    "id":"64120015",
    "test":"1234"
}

dic["name"] = "tanupat aod"
del dic["test"]

for i in dic:
  print(i," : ",dic[i])

"""# 16 Read  positive negative zero integers from input and quit by 9999 then print positive number negetive number and zero number """

b=[]
while True :
  a = int(input("insert number :"))
  if a == 9999 :
    break
  else:
    b.append(a)
  
print(b)
for i in b:
  if i < 0:
    print(i , "is negative number")
  elif i == 0:
    print(i , "is zero number")
  else :
    print(i , "is positive number")



"""# 17 Build Random Number from 00 to 99 by random ( 24 times ) to list with no repeat value in list"""

from random import random , randint

a=[]
res = []
while True:
  value = randint(0, 99)
  if value in a:
    value = randint(0, 99)
  else:
    a.append(int(value))
  for x in a:
      if x not in res:
          res.append(x)
  if len(a) >= 24:
    break
print(a)

"""# 18 โปรแกรมคำนวนที่จอดรถ โดยให้รับค่า input 10 ครั้ง โดยค่าแรกเป็น ชั่วโมง ค่าที่สองเป็นนาที เสร็จแล้วให้คำนวนว่า จอดรถ 1 ชม.แรกฟรี ชั่วโมงที่สอง เสีย 30 บาท ชั่วโมงที่สาม 50 บาท สี่ชั่วโมงขึ้นไป 100 บาท โดยเศษของชั่วโมงให้ปัดขึ้นเป็น ชั่วโมง"""

a = int(input("ชั่วโมง :"))
b = int(input("นาที :"))
b = b/60
a = a+b 
a1 = math.floor(a)
if a1 <= 1:
  print("จอดฟรี")
elif a1 >=2 and a1 < 3:
  print("จ่าย 50 บาท")
else:
  print("จ่าย 100 บาท")

"""# 19 เล่น ทอยลูกเต๋า 3 ลูก ให้พิมพ์ค่าลูกเต๋าแต่ละลูก และบอกด้วยว่า Hi หรือ Low"""

a = 0
for i in range(1,4):
  value = randint(1,6)
  print("ลูกที่ " , i , "ออก " , value)
  if value <= 3:
    print("ลุกที่" ,i,"ต่ำ")
  else:
    print("ลุกที่" ,i,"สูง")
  a = a + value
if a <=9:
  print("ผลรวม LOW")
else:
  print("ผลรวม HIGH")

"""# 20 Power diagnostic"""

print("0 is True , 1 is False")
has_power = int(input("has_power: 0 or 1"))
is_plugged_in = int(input("is_plugged_in: 0 or 1"))
is_switch_on = int(input("is_switch_on: 0 or 1"))
is_fuse_ok = int(input("is_fuse_ok: 0 or 1"))

if has_power == 0 :
  print("seek other help")
else:
  if is_plugged_in != 0:
    print("plug it in")
  else:
    if is_switch_on != 0 :
      print("turn switch on")
    else:
      if is_fuse_ok != 0:
        print("check fuse")
      else:
        print("seek other help")

"""# 21 จงเขียนโปรแกรมแบบ OOP โดยมีการกำหนดคลาส (class) 2 คลาส คือสุนัข กับแมว  จากนั้นทำการสร้างออปเจ็กต์มาอย่างละ 1 ตัว โดยไม่ต้องกำหนดค่าใดๆ  ในแต่ละคลาส มีรูปแบบดังนี้		
Properties (ต้องกำหนดประเภทของตัวแปรให้เหมาะสม)
		– สายพันธ์ 
		– อายุ
 		– น้ำหนัก 
		– เพศ
Method (ทำการประกาศ โดยไม่ต้องกำหนดการทำงาน)
		– เดินไปข้างหน้า 
		– เดินไปข้างหลัง 
		– กินอาหาร
 
"""

class dog:
  def __init__(self,species,age,weight,sex) :
    self.species = species
    self.age = age
    self.weight = weight
    self.sex = sex
  def walk_front(self) :
    print("หมาตัวนี้ได้เดินไปข้างหน้า")
  def walk_back(self):
    print("หมาตัวนี้ได้ถอยหลัง")
  def eat(self):
    print("หมาตัวนี้ได้กินอาหาร")



class cat:
  def __init__(self,species,age,weight,sex) :
    self.species = species
    self.age = age
    self.weight = weight
    self.sex = sex
  def walk_front(self) :
    print("แมวตัวนี้ได้เดินไปข้างหน้า")
  def walk_back(self):
    print("แมวตัวนี้ได้ถอยหลัง")
  def eat(self):
    print("แมวตัวนี้ได้กินอาหาร")

dog1 = dog("ชิสุ",3,21,"male")
cat1 = cat("แมวส้ม",2,12,"female")
print(dog1.species)
print(cat1.species)
dog1.eat()
cat1.walk_back()

  # def front

  # def back

  # def eat